name: 'Nightly'

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'
  workflow_dispatch:

jobs:
  stat:
    if: github.repository_owner == 'withastro'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code using Git
        uses: actions/checkout@v2

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install NPM Dependencies
        run: pnpm install
        env:
          CI: true

      - name: Collect stats
        run: node scripts/stats/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[ci] collect stats'
          branch: ${{ github.head_ref }}

  lockfile:
    if: github.repository_owner == 'withastro'
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out code using Git
        uses: actions/checkout@v2
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      
      - name: Install NPM Dependencies
        run: pnpm upgrade --recursive
        env:
          CI: true
      
      - name: Create Pull Request
        id: createpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ci/lockfile
          token: ${{ secrets.NIGHTLY_PERSONAL_GITHUB_TOKEN }}
          commit-message: '[ci] update lockfile'
          title: '[ci] update lockfile'
          body: >
            This PR is auto-generated by a nightly GitHub action. 
            It should automatically be merged if tests pass.
